version: '3.8'

services:
  
  db:
    image: postgres:alpine3.14
    container_name: dictdb
    restart: always
    volumes:
      - dictdbvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - core/.env
  
  app:
    build: .
    volumes:
      - .:/app
    image: dict:django
    container_name: dictapp
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  dictdbvolume: